export const browserRoutes = {
  LOGIN: "/",
  SIGN_UP: "/signup",
  ADMIN_LOGIN: "/admin-login",
  VERIFY_OTP: "/verify-otp",
  VERIFY_OTP_PASSWORD: "/password_verify-otp",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_PHONE_NUMBER: "/verify-phone-number",
  CREATE_PASSWORD: "/create-password",
  CREATE_NEW_PASSWORD: "/create-new-password",
  DASHBOARD: "/dashboard",
  WALLET: "/wallet",
  ADD_CONTACT: "/add-contact",
  ADD_CARD: "/wallet/add-card",
  ADD_BANK: "/wallet/add-bank",
  PORTFOLIO: "/portfolio",
  RESET_PASSWORD: "/reset-password",
  REWARDS: "/rewards",
  CART: "/cart",
  PROFILE: "/profile",
  ACCOUNT_INFORMATION: "/account-information",
  ACCOUNT_PREFERENCE: "/account-preference",
  SECURITY_PRIVACY: "/security-and-privacy",
  RAFER_A_FRIEND: "/refer-friend",

  // Admin routes

  PROPERTIES: "/properties",
  USERS: "/users",
  TOKEN: "/tokens",
  KYC: "/kyc",
  USER_KYC: "/user-kyc",
  PAYMENTS: "/payments",
  CREATE_PROPERTIES: "/properties/create",
  DRAFT_PROPERTIES: "/properties/draft",
  CREATE_TOKEN: "/tokens/create",
  UPDATE_PROPERTIES: "/properties/edit",
  PROPERTIES_DETAILS: "/properties/details",
};
