export const serverRoutes = {
  SIGN_UP: "users/create-account",
  LOGIN: "users/login",
  VERIFY_OTP: "users/verify-email",
  FORGOT_PASSWORD: "users/reset-password/email",
  FORGOT_PASSWORD_OTP: "users/reset-password/otp",
  UPDATE_PASSWORD: "users/reset-password",
  CREATE_PASSWORD: "users/create-password",
  ADD_CONTACT: "users/add-contact",
  VERIFY_PHONE_NUMBER: "users/verify-contact",
  GET_ALL_PROPERTY: "properties/all",
  ADD_CARD: "user/card/add",
  GET_ALL_CARD: "user/card/all",
  DELETE_CARD: "user/card/delete",
  ADD_BANK: "user/bank/add",
  GET_ALL_BANK: "user/bank/all",
  DELETE_BANK: "user/bank/delete",
  GET_USER: "users/me",
  GET_ALL_TOKENS: "token/all",
  ADD_TOKEN: "token/add",
  START_SALE: "sale/add",
  FINALISE_SALE: "sale/finalize",
  SUBMIT_KYC: "users/submit-kyc",
  WITHDRAW_FUNDS: "users/withdraw-funds",
  GET_WALLET_TRANSACTIONS: "/users/fetch-user-transaction",
  RESEND_OTP: "/users/resendOtp",

  // Admin routes
  CREATE_PROPERTY: "properties/add",
  GET_SINGLE_PROPERTY: "properties",
  UPDATE_PROPERTY: "properties/update",
  DELETE_PROPERTY: "properties/delete",
  GET_ALL_USERS: "users/all-users",
  PURCHASE_PROPERTY: "purchase",
  // GET_USER_PURCHASE: "here would be the route",
  CLAIM: "claim",
  GET_ALL_KYC_REQUESTS: "users/all-kyc-requests",
  UPDATE_KYC_STATUS: "users/review-kyc",
  GET_WALLET_BALANCE: "users/getbalance",
};
